#!/bin/bash -exu

export RELEASE_VERSION="99999+dev.$(date +%s)"

function main() {
  pushd release > /dev/null
    bosh -t ${BOSH_DIRECTOR} create release --force --version ${RELEASE_VERSION}
  popd > /dev/null
}

main
