groups:
- name: dnsmasq
  jobs:
  - deploy-dnsmasq

resources:
- name: mega-ci
  type: git
  source:
    branch: testing-dnsmasq
    uri: https://github.com/cloudfoundry/mega-ci.git
- name: dnsmasq-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry-incubator/dnsmasq-release.git
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: bosh-deployment
  type: bosh-deployment-resource
  source:
    target: {{bosh_director}}
    username: {{bosh_username}}
    password: {{bosh_password}}
    deployment: dnsmasq

jobs:
- name: deploy-dnsmasq
  public: true
  plan:
  - aggregate:
    - get: mega-ci
    - get: release
      resource: dnsmasq-release-develop
      trigger: true
    - get: stemcell
      resource: aws-stemcell
  - task: create-dev-release
    file: mega-ci/scripts/ci/create-dev-release/task.yml
    config:
      params:
        BOSH_DIRECTOR: {{bosh_director}}
        BOSH_USER: {{bosh_username}}
        BOSH_PASSWORD: {{bosh_password}}
  - put: bosh-deployment
    params:
      manifest: dnsmasq-release/ci/assets/test-manifest.yml
      stemcells:
      - stemcell/stemcell.tgz
      releases:
      - release/release.tgz
